pipeline {
    agent any

    parameters {
        booleanParam(name: 'SKIP_BUILD', defaultValue: false, description: 'Skip Docker image build')
    }

    environment {
        DOCKERHUB_CREDENTIALS = credentials('dockerhub')
        IMAGE_NAME = "abdo1997mohamed2030/comingsoon-page:latest"
        APP_DIR = "DevOps-Pipeline-PHP/laravel-app"
    }

    stages {
        stage('Docker Login') {
            steps {
                sh """
                    echo $DOCKERHUB_CREDENTIALS_PSW | docker login -u $DOCKERHUB_CREDENTIALS_USR --password-stdin
                """
            }
        }

        stage('Build Docker Image') {
            when {
                expression { return !params.SKIP_BUILD }
            }
            steps {
                dir("${APP_DIR}") {
                    sh "docker build -t ${IMAGE_NAME} ."
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                sh "docker push ${IMAGE_NAME}"
            }
        }

        stage('Run Docker Compose') {
            steps {
                dir("${APP_DIR}") {
                    sh "docker-compose up -d --build"
                }
            }
        }
    }

    post {
        always {
            echo "Cleaning up dangling images..."
            sh "docker image prune -f"
        }
    }
}