---
- name: "Build, tag and push Docker image"
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Stop running container if exists
      command: docker stop laravel-container
      ignore_errors: yes

    - name: Remove stopped container
      command: docker rm laravel-container
      ignore_errors: yes

    - name: Remove old image if exists
      command: docker rmi abdo1997.mohamed2030/laravel-app
      ignore_errors: yes

    - name: Build Docker image
      command: docker build -t abdo1997.mohamed2030/laravel-app .

    - name: Push Docker image to DockerHub
      command: docker push abdo1997.mohamed2030/laravel-app