---
- name: "Run Docker Compose and Composer Update"
  hosts: localhost
  gather_facts: no
  vars:
    php_container_name_pattern: "php-apache"  # Part of container name
    max_retries: 10
    retry_delay: 3
  tasks:

    - name: Stop and remove all containers if exist
      command: docker-compose down
      args:
        chdir: "{{ playbook_dir }}"
      ignore_errors: yes

    - name: Remove Laravel app image (ignore if not exist)
      command: docker rmi abdo1997.mohamed2030/laravel-app
      ignore_errors: yes

    - name: Remove php-apache image (ignore if not exist)
      command: docker rmi php:8.2-apache
      ignore_errors: yes

    - name: Remove MySQL image (ignore if not exist)
      command: docker rmi mysql:5.7
      ignore_errors: yes

    - name: Remove phpMyAdmin image (ignore if not exist)
      command: docker rmi phpmyadmin/phpmyadmin
      ignore_errors: yes

    - name: Build and start Docker Compose
      command: docker-compose up -d
      args:
        chdir: "{{ playbook_dir }}"

    - name: Wait for PHP container to start
      shell: docker ps --filter "name={{ php_container_name_pattern }}" --format '{{.Names}}'
      register: php_container
      retries: "{{ max_retries }}"
      delay: "{{ retry_delay }}"
      until: php_container.stdout != ""

    - name: Run composer update inside PHP container
      shell: docker exec -i {{ php_container.stdout }} sh -c "composer install --no-interaction --optimize-autoloader"