pipeline {
    agent any

    environment {
        DOCKERHUB_CREDENTIALS = credentials('dockerhub')
    }

    stages {
        stage('Docker Login') {
            steps {
                script {
                    retry(3) { // Retry login up to 3 times if it fails
                        sh '''
                        echo $DOCKERHUB_CREDENTIALS_PSW | docker login -u $DOCKERHUB_CREDENTIALS_USR --password-stdin
                        '''
                    }
                }
            }
        }

        stage('Build & push Dockerfile') {
            steps {
                sh '''
                cd Kubernetes/comingsoon/
                ansible-playbook playbook.yml
                '''
            }
        }

        stage('Delete Cluster') {
            steps {
                withCredentials([[
                    $class: 'AmazonWebServicesCredentialsBinding',
                    credentialsId: "aws-credentials",
                    accessKeyVariable: 'AWS_ACCESS_KEY_ID',
                    secretKeyVariable: 'AWS_SECRET_ACCESS_KEY'
                ]]) {
                    sh '''
                    eksctl delete cluster --name comingsoon-cluster --region eu-north-1 || true
                    sleep 180
                    '''
                }
            }
        }

        stage('Create Cluster') {
            steps {
                withCredentials([[
                    $class: 'AmazonWebServicesCredentialsBinding',
                    credentialsId: "aws-credentials",
                    accessKeyVariable: 'AWS_ACCESS_KEY_ID',
                    secretKeyVariable: 'AWS_SECRET_ACCESS_KEY'
                ]]) {
                    sh '''
                    eksctl create cluster --name comingsoon-cluster --region eu-north-1 --nodes-min=1
                    aws eks update-kubeconfig --name comingsoon-cluster
                    '''
                }
            }
        }

        stage('Create Namespace') {
            steps {
                withCredentials([[
                    $class: 'AmazonWebServicesCredentialsBinding',
                    credentialsId: "aws-credentials",
                    accessKeyVariable: 'AWS_ACCESS_KEY_ID',
                    secretKeyVariable: 'AWS_SECRET_ACCESS_KEY'
                ]]) {
                    sh 'kubectl create namespace comingsoon || true'
                }
            }
        }

        stage('Deploy') {
            steps {
                withCredentials([[
                    $class: 'AmazonWebServicesCredentialsBinding',
                    credentialsId: "aws-credentials",
                    accessKeyVariable: 'AWS_ACCESS_KEY_ID',
                    secretKeyVariable: 'AWS_SECRET_ACCESS_KEY'
                ]]) {
                    sh '''
                    cd Kubernetes/comingsoon/k8s
                    kubectl -n comingsoon apply -f deployment.yaml
                    kubectl -n comingsoon apply -f services.yaml
                    '''
                }
            }
        }
    }
}