---
- name: "Build and deploy Docker container"
  hosts: localhost
  connection: local

  vars:
    docker_image_name: "abdo1997mohamed2030/comingsoon-page"
    docker_container_name: "web-container"
    docker_host_port: 5000
    docker_container_port: 80

  tasks:
    - name: Stop running container if it exists
      shell: |
        if [ "$(docker ps -q -f name={{ docker_container_name }})" ]; then
          docker stop {{ docker_container_name }}
        fi
      ignore_errors: yes

    - name: Remove container if it exists
      shell: |
        if [ "$(docker ps -aq -f name={{ docker_container_name }})" ]; then
          docker rm {{ docker_container_name }}
        fi
      ignore_errors: yes

    - name: Remove image if it exists
      shell: |
        if [ "$(docker images -q {{ docker_image_name }})" ]; then
          docker rmi {{ docker_image_name }}
        fi
      ignore_errors: yes

    - name: Build Docker image
      shell: docker build -t {{ docker_image_name }} .

    - name: Push image to Docker Hub
      shell: docker push {{ docker_image_name }}

    - name: Run Docker container
      shell: docker run -d --name {{ docker_container_name }} -p {{ docker_host_port }}:{{ docker_container_port }} {{ docker_image_name }}