---
- name: "Build and deploy Docker container"
  hosts: localhost
  connection: local

  vars:
    docker_image_name: "abdo1997mohamed2030/comingsoon-page"
    docker_container_name: "web-container"
    docker_host_port: 5000
    docker_container_port: 80

  tasks:
    - name: Stop current running container
      command: docker stop {{ docker_container_name }}
      ignore_errors: yes

    - name: Remove stopped container
      command: docker rm {{ docker_container_name }}
      ignore_errors: yes

    - name: Remove existing image
      command: docker rmi {{ docker_image_name }}
      ignore_errors: yes

    - name: Build Docker image
      command: docker build -t {{ docker_image_name }} .

    - name: Push image to Docker Hub
      command: docker push {{ docker_image_name }}

    - name: Run container
      command: docker run -d --name {{ docker_container_name }} -p {{ docker_host_port }}:{{ docker_container_port }} {{ docker_image_name }}