pipeline {
    agent any

    environment {
        DOCKERHUB_CREDENTIALS = credentials('dockerhub')
    }

    stages {
        stage('Docker Login') {
            steps {
                sh 'echo $DOCKERHUB_CREDENTIALS_PSW | docker login -u $DOCKERHUB_CREDENTIALS_USR --password-stdin'
            }
        }

        stage('Run Ansible Playbook on Host') {
            steps {
                // Use absolute path to your project folder on the EC2 host
                sh """
                cd /home/ubuntu/Simple-Project
                ansible-playbook ansible-playbook.yml \
                  -e docker_image_name=abdo1997mohamed2030/comingsoon-page \
                  -e docker_container_name=web-container \
                  -e docker_host_port=5000 \
                  -e docker_container_port=80
                """
            }
        }

        stage('Verify Deployment') {
            steps {
                sh 'docker ps'
            }
        }
    }
}